version: '3.8'

services:
  api:
    build:
      context: ./api
    image: challenge-produza-container-api
    ports:
      - "8009:8009"
    volumes:
      - ./api:/app
    environment:
      - NODE_ENV=development
    env_file:
      - ./api/.env

  frontend:
    build:
      context: ./frontend
    image: challenge-produza-container-frontend
    ports:
      - "4000:4000"
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
    env_file:
      - ./frontend/.env